['all']
enabled_layers = ["main", "grime"]
['ironchest/textures/model/chest/gold_chest.png']
enabled_layers = ["gold"]
['ironchest/textures/model/chest/diamond_chest.png']
enabled_layers = ["diamond"]
