#['ironchest/textures/model/chest/gold_chest.png']
['all']
enabled_layers = ["main", "grime"]
['gold_chest.png']
enabled_layers = ["gold"]
#['ironchest/textures/model/chest/diamond_chest.png']
['diamond_chest.png']
enabled_layers = ["diamond"]
